org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true

# NDK
android.ndkVersion=26.2.11394342
android.ndkPath=/opt/android-sdk/ndk/26.2.11394342
android.cmake.version=3.22.1

# Optimize
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
